[metadata]
name = pynst
version = 0.0.1
author = Michael Loose, FAU Erlangen-Nürnberg (LITES)
description = Toolkit for managing nested sweeps in Python
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages = find:
python_requires = >=3.8
install_requires =
    pyserial
    pandas
    numpy
    tqdm
    tables

[options.extras_require]
dev =
    flake8
    mypy
    ipython
    jupyter

