"""Helpers for defining reproducible one- and two-dimensional ranges.

The functions in this module retain the range API historically provided by
``MultiADSweep.simpoints``.  Unlike ``numpy.arange``, the requested bounds are
treated as authoritative: when a step does not divide the span exactly, the
step is adjusted and a warning is emitted.
"""

from __future__ import annotations

from collections.abc import Iterable
import math
from numbers import Integral, Real
from typing import Any
import warnings

import numpy as np


_RANGE_KEYS = ("center", "span", "min", "max", "step", "num")
_X_SUFFIXES = ("_x", "_re", "_r")
_Y_SUFFIXES = ("_y", "_im", "_i")


def _real_scalar(value: Any, *, name: str) -> float:
    """Return *value* as a finite real scalar."""
    if isinstance(value, (bool, np.bool_)) or not isinstance(value, Real):
        raise ValueError(f"{name!r} must be a real scalar.")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{name!r} must be finite.")
    return result


def _point_count(value: Any) -> int:
    if isinstance(value, (bool, np.bool_)) or not isinstance(value, Integral):
        raise ValueError("'num' must be an integer.")
    result = int(value)
    if result < 1:
        raise ValueError("'num' must be >= 1.")
    return result


def _round_if_requested(value: float, *, enabled: bool, decimals: int) -> float:
    return round(value, decimals) if enabled else value


def define_range(
    center: float | None = None,
    span: float | None = None,
    min: float | None = None,
    max: float | None = None,
    step: float | None = None,
    num: int | None = None,
    endpoint: bool = True,
    round_output: bool = True,
    decimals: int = 8,
) -> dict[str, float | int]:
    """Resolve a complete description of an evenly sampled range.

    Supply either ``center`` and ``span`` or ``min`` and ``max``, and exactly
    one of ``step`` or ``num``.  If ``step`` does not divide the requested span
    exactly, the nearest positive number of intervals is used and the adjusted
    step is reported with :class:`UserWarning`.

    ``endpoint=False`` describes the half-open samples produced by
    :func:`create_range`; ``max`` remains the requested upper boundary.  A
    one-point range contains its lower bound, matching ``numpy.linspace``.

    Returns:
        A dictionary containing ``center``, ``span``, ``min``, ``max``,
        ``step`` and ``num``.
    """
    if not isinstance(endpoint, (bool, np.bool_)):
        raise TypeError("'endpoint' must be a boolean.")
    if not isinstance(round_output, (bool, np.bool_)):
        raise TypeError("'round_output' must be a boolean.")
    if isinstance(decimals, (bool, np.bool_)) or not isinstance(decimals, Integral):
        raise ValueError("'decimals' must be a non-negative integer.")
    decimals = int(decimals)
    if decimals < 0:
        raise ValueError("'decimals' must be a non-negative integer.")

    bounds_by_center = center is not None or span is not None
    bounds_by_limits = min is not None or max is not None
    if bounds_by_center and bounds_by_limits:
        raise ValueError(
            "Provide either 'center'/'span' or 'min'/'max', not both."
        )
    if bounds_by_center:
        if center is None or span is None:
            raise ValueError("Both 'center' and 'span' are required.")
        resolved_center = _real_scalar(center, name="center")
        resolved_span = _real_scalar(span, name="span")
        if resolved_span < 0:
            raise ValueError("'span' must be non-negative.")
        lower = resolved_center - resolved_span / 2
        upper = resolved_center + resolved_span / 2
    elif bounds_by_limits:
        if min is None or max is None:
            raise ValueError("Both 'min' and 'max' are required.")
        lower = _real_scalar(min, name="min")
        upper = _real_scalar(max, name="max")
        if upper < lower:
            raise ValueError("'max' must be greater than or equal to 'min'.")
        resolved_span = upper - lower
        resolved_center = (lower + upper) / 2
    else:
        raise ValueError(
            "Provide either 'center'/'span' or 'min'/'max' to define a range."
        )

    if (step is None) == (num is None):
        raise ValueError("Provide exactly one of 'step' or 'num'.")

    if num is not None:
        resolved_num = _point_count(num)
        if resolved_num == 1:
            # A singleton generated by linspace is the lower bound.  Normalise
            # all returned geometry so the description matches the samples.
            upper = lower
            resolved_center = lower
            resolved_span = 0.0
            resolved_step = 0.0
        else:
            if resolved_span == 0:
                raise ValueError("A zero-span range can contain only one point.")
            divisor = resolved_num - 1 if endpoint else resolved_num
            resolved_step = resolved_span / divisor
    else:
        requested_step = _real_scalar(step, name="step")
        if requested_step <= 0:
            raise ValueError("'step' must be positive.")
        if resolved_span == 0:
            resolved_num = 1
            resolved_step = 0.0
        else:
            approximate_intervals = resolved_span / requested_step
            # Round halves up rather than using Python's banker rounding.
            interval_count = math.floor(approximate_intervals + 0.5)
            if interval_count < 1:
                interval_count = 1
            resolved_num = interval_count + 1 if endpoint else interval_count
            divisor = resolved_num - 1 if endpoint else resolved_num
            resolved_step = resolved_span / divisor
            tolerance = abs(requested_step) * 1e-12
            if tolerance < 1e-12:
                tolerance = 1e-12
            if not math.isclose(
                resolved_step,
                requested_step,
                rel_tol=1e-12,
                abs_tol=tolerance,
            ):
                warnings.warn(
                    f"Adjusting 'step' from {requested_step} to "
                    f"{resolved_step} to fit within 'span'.",
                    UserWarning,
                    stacklevel=2,
                )
            if resolved_num == 1:
                upper = lower
                resolved_center = lower
                resolved_span = 0.0
                resolved_step = 0.0

    numeric = {
        "center": resolved_center,
        "span": resolved_span,
        "min": lower,
        "max": upper,
        "step": resolved_step,
    }
    result: dict[str, float | int] = {
        key: _round_if_requested(value, enabled=round_output, decimals=decimals)
        for key, value in numeric.items()
    }
    result["num"] = resolved_num
    return result


def create_range(
    center: float | None = None,
    span: float | None = None,
    min: float | None = None,
    max: float | None = None,
    step: float | None = None,
    num: int | None = None,
    endpoint: bool = True,
    round_output: bool = True,
    decimals: int = 8,
) -> np.ndarray:
    """Create the samples described by :func:`define_range`.

    This is the compatible replacement for
    ``MultiADSweep.simpoints.create_range``.
    """
    definition = define_range(
        center=center,
        span=span,
        min=min,
        max=max,
        step=step,
        num=num,
        endpoint=endpoint,
        round_output=round_output,
        decimals=decimals,
    )
    values = np.linspace(
        definition["min"],
        definition["max"],
        int(definition["num"]),
        endpoint=endpoint,
        dtype=float,
    )
    return np.round(values, decimals) if round_output else values


def _split_general_value(value: Any, *, name: str) -> tuple[Any, Any]:
    if isinstance(value, (complex, np.complexfloating)):
        return float(np.real(value)), float(np.imag(value))
    if isinstance(value, (str, bytes)):
        raise ValueError(
            f"{name!r} must be a scalar, complex number, or two values."
        )
    if isinstance(value, Iterable) and not isinstance(value, Real):
        values = tuple(value)
        if len(values) != 2:
            raise ValueError(f"{name!r} must contain exactly two values.")
        return values[0], values[1]
    if isinstance(value, Real) and not isinstance(value, (bool, np.bool_)):
        return value, value
    raise ValueError(
        f"{name!r} must be a scalar, complex number, or two values."
    )


def _axis_key(key: str) -> tuple[str, str] | None:
    for suffix in _X_SUFFIXES:
        if key.endswith(suffix):
            return "x", key[: -len(suffix)]
    for suffix in _Y_SUFFIXES:
        if key.endswith(suffix):
            return "y", key[: -len(suffix)]
    return None


def define_area(
    endpoint: bool = True,
    round_output: bool = True,
    decimals: int = 8,
    **kwargs: Any,
) -> dict[str, float | int]:
    """Resolve independent range definitions for a two-dimensional area.

    Unsuffixed arguments apply to both axes.  A scalar is repeated, a complex
    number is split into real and imaginary parts, and a two-item iterable is
    split into x and y values.  Axis-specific arguments (for example
    ``center_x`` or ``center_im``) override their unsuffixed counterpart.

    The compatible suffixes are ``_x``/``_re``/``_r`` and
    ``_y``/``_im``/``_i``.
    """
    valid = set(_RANGE_KEYS)
    valid.update(
        base + suffix
        for base in _RANGE_KEYS
        for suffix in (*_X_SUFFIXES, *_Y_SUFFIXES)
    )
    unexpected = sorted(set(kwargs) - valid)
    if unexpected:
        raise TypeError(
            f"define_area() got an unexpected keyword argument "
            f"{unexpected[0]!r}"
        )

    general: dict[str, Any] = {}
    specific: dict[str, dict[str, Any]] = {"x": {}, "y": {}}
    supplied_alias: dict[tuple[str, str], str] = {}
    for key, value in kwargs.items():
        axis_key = _axis_key(key)
        if axis_key is None:
            general[key] = value
            continue
        axis, base = axis_key
        marker = (axis, base)
        if marker in supplied_alias:
            raise ValueError(
                f"Conflicting aliases {supplied_alias[marker]!r} and {key!r}."
            )
        supplied_alias[marker] = key
        specific[axis][base] = value

    params_x: dict[str, Any] = {}
    params_y: dict[str, Any] = {}
    for key, value in general.items():
        value_x, value_y = _split_general_value(value, name=key)
        params_x[key] = value_x
        params_y[key] = value_y
    params_x.update(specific["x"])
    params_y.update(specific["y"])

    try:
        range_x = define_range(
            endpoint=endpoint,
            round_output=round_output,
            decimals=decimals,
            **params_x,
        )
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Invalid x-axis range: {exc}") from exc
    try:
        range_y = define_range(
            endpoint=endpoint,
            round_output=round_output,
            decimals=decimals,
            **params_y,
        )
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Invalid y-axis range: {exc}") from exc

    return {
        **{f"{key}_x": value for key, value in range_x.items()},
        **{f"{key}_y": value for key, value in range_y.items()},
    }


__all__ = ["create_range", "define_area", "define_range"]
